### ISSUE TITLE
pre vs. post hooks

### ISSUE THREAD

**Issue by Uzlopak** [mongoosejs/kareem#26]
Is there a reason why pre can handle async but post can not?

**Comment by vkarpov15** [comment]
What makes you think post hooks can't handle async? Here's an example from our docs: https://github.com/vkarpov15/kareem#it-supports-returning-a-promise-1

**Comment by Uzlopak** [comment]
I was looking if I could streamline pre and post function but pre is handling async stuff but post is not.

**Comment by hasezoey** [comment]
@Uzlopak is this "post hooks cannot handle async" based on that `pre` has `isAsync` but `post` has not?

**Comment by Uzlopak** [comment]
Yes
